live_config_reload = true
working_directory = "None"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '#1E1E2E' # base
foreground = '#CDD6F4' # text
# Bright and dim foreground colors
dim_foreground = '#CDD6F4'    # text
bright_foreground = '#CDD6F4' # text

# Cursor colors
[colors.cursor]
text = '#1E1E2E'   # base
cursor = '#F5E0DC' # rosewater

[colors.vi_mode_cursor]
text = '#1E1E2E'   # base
cursor = '#B4BEFE' # lavender

# Search colors
[colors.search.matches]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

[colors.search.focused_match]
foreground = '#1E1E2E' # base
background = '#A6E3A1' # green

[colors.footer_bar]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

# Keyboard regex hints
[colors.hints.start]
foreground = '#1E1E2E' # base
background = '#F9E2AF' # yellow

[colors.hints.end]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

# Selection colors
[colors.selection]
text = '#1E1E2E'       # base
background = '#F5E0DC' # rosewater

# Normal colors
[colors.normal]
black = '#45475A'   # surface1
red = '#F38BA8'     # red
green = '#A6E3A1'   # green
yellow = '#F9E2AF'  # yellow
blue = '#89B4FA'    # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5'    # teal
white = '#BAC2DE'   # subtext1

# Bright colors
[colors.bright]
black = '#585B70'   # surface2
red = '#F38BA8'     # red
green = '#A6E3A1'   # green
yellow = '#F9E2AF'  # yellow
blue = '#89B4FA'    # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5'    # teal
white = '#A6ADC8'   # subtext0

# Dim colors
[colors.dim]
black = '#45475A'   # surface1
red = '#F38BA8'     # red
green = '#A6E3A1'   # green
yellow = '#F9E2AF'  # yellow
blue = '#89B4FA'    # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5'    # teal
white = '#BAC2DE'   # subtext1

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 13.0
builtin_box_drawing = false

[font.glyph_offset]
x = 0
y = 0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Shift"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["-l", "-c", "tmux"]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "Maximized"
title = "Alacritty"

[window.padding]
x = 12
y = 12
